### ISSUE TITLE
running two or more instances of rtc server breaks the heroku instance

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/nodelab#11]
From @jon-Silveira 's message in our discord:

> i made another heroku that handles the exchanges for the audio stuff and pushed it to deploy, it does work on the alicelab heroku but if someone does "node server.js" locally it will break the Heroku server that's handling the audio exchanges ...is it possible to have multiple ports on xr.alicelab.world? it says "websocket.js:89 WebSocket connection to 'wss://xr.alicelab.world:3123/socket.io/?EIO=4&transport=websocket' failed:"

Do we need to run the RTC server within server.js, or can we just make a new repo for it and run it as its own cloud instance? that way its always running (or in the case of heroku, is always reachable and wakeable).

**Comment by michaelpalumbo** [comment]
working on it...

https://github.com/worldmaking/nodelab-rtc

**Comment by jon-Silveira** [comment]
Connecting multiple clients (hosted on different servers ) causes security issues (attached below), in the latest commit "5d75364" the solution was to create a dynamic room inside https://agile-basin-71343.herokuapp.com using ` let room = location.hostname` on join. So localhost will create rooms called "localhost", "alicelab.herokuapp.com" etc. Though an issue may occur when two localhost servers attempt to connect though the same "localhost" room to be tested may not effect the other rooms
![unknown](https://user-images.githubusercontent.com/26636838/144298970-87d2c386-a088-4f2f-839d-48427c9fde87.png)

**Comment by michaelpalumbo** [comment]
> Connecting multiple clients (hosted on different servers ) causes security issues (attached below), in the latest commit "5d75364" the solution was to create a dynamic room inside https://agile-basin-71343.herokuapp.com using ` let room = location.hostname` on join. So localhost will create rooms called "localhost", "alicelab.herokuapp.com" etc. Though an issue may occur when two localhost servers attempt to connect though the same "localhost" room to be tested may not effect the other rooms ![unknown](https://user-images.githubusercontent.com/26636838/144298970-87d2c386-a088-4f2f-839d-48427c9fde87.png)

Nicely done @jon-Silveira I'm going to close this issue.
