### ISSUE TITLE
alternative to .env when running server locally?

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/nodelab#8]
At present, the .env file for configuring networking is listed in the .gitignore. I think this makes sense, as for security reasons it's good to not have .env files hosted in public repos. But we'll need a workaround for when someone wants to run the server.js locally. One option is to use a startup cli flag, like npm start --local to tell the script to run locally with predefined variables for that context. @DMGregory would you dm me the .env file details so I make sure I'm setting this up correctly?

**Comment by DMGregory** [comment]
@michaelpalumbo I don't seem to have a .env file locally.

**Comment by michaelpalumbo** [comment]
@DMGregory oh weird. weren't you working with one last week when we were refactoring connect.js to merge.js? I think we went over that when deciding to what to do with the port number config for heroku or computer canada?

**Comment by DMGregory** [comment]
@michaelpalumbo I don't remember that. I think everything we looked at port-wise was in server.js.

**Comment by n1ckfg** [comment]
The idea was to have three modes, each with their own http and port configs: .env for Heroku, .env for Alice (Compute Canada), and if there's no env it defaults to localhost.

**Comment by michaelpalumbo** [comment]
ah i'm gettign my meetings crossed. This discussion was with @n1ckfg last week. Sorry about that. Ok, I'm closing this issue and will open a more relevant one

**Comment by michaelpalumbo** [comment]
Ah that was it, thanks for clarifying Nick. Is there a branch where this is
implemented?

**Comment by michaelpalumbo** [comment]
Am opening this back up as per recent discussion

**Comment by n1ckfg** [comment]
Yup, it's on main, just pulled and restarted the Alice server to check

**Comment by michaelpalumbo** [comment]
Excellent. thanks @n1ckfg 

Since we're using _main_ for CC server, _develop_ for heroku, some point today i'll merge that .env into develop and ensure it still runs on heroku

**Comment by DMGregory** [comment]
I think you can also set the environment variables on Heroku directly, in case we don't want a platform-specific file in the git repo (not sure if that messes with any of the other platforms?) https://catalins.tech/heroku-environment-variables

**Comment by n1ckfg** [comment]
Shall we rewrite the startup port logic to simplify things? Heroku / localhost if no .env, Alice setup if .env. See example here: https://github.com/worldmaking/nodelab/tree/nick-dev

**Comment by michaelpalumbo** [comment]
@jon-Silveira identified that heroku can't have more than one port open. this may lead to a solution: https://stackoverflow.com/questions/37636580/heroku-node-js-i-have-a-server-which-uses-multiple-ports-how-can-i-get-herok

**Comment by michaelpalumbo** [comment]
Solved by @n1ckfg today:

```javascript
// this will be true if there's no .env file
const IS_HTTP = (!process.env.PORT_HTTP);

const PORT_HTTP = IS_HTTP ? (process.env.PORT || 3000) : (process.env.PORT_HTTP || 80);
const PORT_HTTPS = process.env.PORT_HTTPS || 443;
const PORT = IS_HTTP ? PORT_HTTP : PORT_HTTPS;
```
